# -*- coding: utf-8 -*-
"""04_Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b017-uRiUkIG9B_bFPgTrxfMkRh41onQ
"""

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %pip install mplfinance

# ===== CÀI ĐẶT VÀ IMPORT THƯ VIỆN =====
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import mplfinance as mpf

# Đọc dữ liệu
data = pd.read_csv("Data_Milk_CLEANED.csv")
data["time"] = pd.to_datetime(data["time"])
data = data.sort_values(["symbol", "time"]).reset_index(drop=True)

# ===== BIỂU ĐỒ 1: Xu hướng giá đóng cửa theo thời gian =====
for s in data["symbol"].unique():
    df = data[data["symbol"] == s]
    plt.plot(df["time"], df["close"], label=s)
plt.title("Xu hướng giá đóng cửa (2020–2025)")
plt.xlabel("Thời gian")
plt.ylabel("Giá đóng cửa (Close)")
plt.legend()
plt.show()

# ===== BIỂU ĐỒ 2: Biến động giá (High - Low) =====
for s in data["symbol"].unique():
    df = data[data["symbol"] == s]
    plt.plot(df["time"], df["range"], label=s)
plt.title("Biến động giá (High−Low)")
plt.xlabel("Thời gian")
plt.ylabel("Biên độ giá")
plt.legend()
plt.show()

# ===== BIỂU ĐỒ 3: So sánh trung bình giá mở và đóng =====
avg_open_close = data.groupby("symbol")[["open", "close"]].mean()
avg_open_close.plot(kind="bar")
plt.title("So sánh trung bình giá Mở (Open) và Đóng (Close)")
plt.ylabel("Giá trung bình (VND)")
plt.show()

# ===== BIỂU ĐỒ 4: Mức tăng trưởng giá (%) =====
trend = data.groupby("symbol").agg(first=("close", "first"), last=("close", "last"))
trend["trend_pct"] = (trend["last"] - trend["first"]) / trend["first"] * 100
trend["trend_pct"].sort_values().plot(kind="barh", color="green")
plt.title("Tăng trưởng giá (%) 2020–2025")
plt.xlabel("Phần trăm tăng (%)")
plt.ylabel("Mã cổ phiếu")
plt.show()

# ===== BIỂU ĐỒ 5: Phân bố khối lượng giao dịch (Histogram) =====
plt.hist(data["volume"], bins=50, color="orange", edgecolor="black")
plt.title("Phân bố khối lượng giao dịch")
plt.xlabel("Volume")
plt.ylabel("Tần suất")
plt.show()

# ===== BIỂU ĐỒ 6: Giá cao nhất của từng cổ phiếu =====
max_high = data.groupby("symbol")["high"].max()
max_high.plot(kind="bar", color="lightcoral")
plt.title("Giá cao nhất từng cổ phiếu (2020–2025)")
plt.xlabel("Mã cổ phiếu")
plt.ylabel("Giá cao nhất (High)")
plt.show()

# ===== BIỂU ĐỒ 7: Giá thấp nhất của từng cổ phiếu =====
min_low = data.groupby("symbol")["low"].min()
min_low.plot(kind="bar", color="teal")
plt.title("Giá thấp nhất từng cổ phiếu (2020–2025)")
plt.xlabel("Mã cổ phiếu")
plt.ylabel("Giá thấp nhất (Low)")
plt.show()

# ===== BIỂU ĐỒ 8: Khối lượng giao dịch theo thời gian =====
for s in data["symbol"].unique():
    df = data[data["symbol"] == s]
    plt.plot(df["time"], df["volume"], label=s)
plt.title("Khối lượng giao dịch theo thời gian")
plt.xlabel("Thời gian")
plt.ylabel("Volume")
plt.legend()
plt.show()

# ===== BIỂU ĐỒ 9: Lợi nhuận nội ngày (Close - Open) =====
data["daily_return"] = data["close"] - data["open"]
for s in data["symbol"].unique():
    df = data[data["symbol"] == s]
    plt.plot(df["time"], df["daily_return"], label=s)
plt.title(" Lợi nhuận nội ngày (Close - Open)")
plt.xlabel("Thời gian")
plt.ylabel("Lợi nhuận (VND)")
plt.legend()
plt.show()

# ===== BIỂU ĐỒ 10: Tương quan giữa giá Mở và giá Đóng =====
plt.scatter(data["open"], data["close"], alpha=0.5, color="purple")
plt.title(" Tương quan giữa giá Mở và Đóng ")
plt.xlabel(" Giá Mở (Open) ")
plt.ylabel(" Giá Đóng (Close) ")
plt.show()

# ===== BIỂU ĐỒ 11: Tương quan giữa biên độ giá và khối lượng =====
plt.scatter(data["range"], data["volume"], alpha=0.5, color="brown")
plt.title(" Tương quan giữa biên độ giá và khối lượng ")
plt.xlabel(" Biên độ giá (High−Low) ")
plt.ylabel(" Khối lượng (Volume) ")
plt.show()

# ===== Biểu đồ 12: Trung vị giá đóng cửa =====
plt.figure()
median_close = data.groupby("symbol")["close"].median()
median_close.plot(kind="barh", color="limegreen")
plt.title("Giá đóng cửa trung vị (Median Close)")
plt.xlabel("Giá trung vị")
plt.show()